# VitFly-AirSim Simulation Configuration

# Simulation Mode
mode: "expert"  # Options: expert, model, data_collection

# AirSim Connection
airsim_host: "127.0.0.1"       # AirSim server host
airsim_port: 41451             # AirSim server port

# Flight Parameters
desired_velocity: 2.0          # Desired forward velocity (m/s) - reduced for safer navigation
flight_altitude: -5.0          # Flight altitude in AirSim coordinates (negative = up)
max_duration: 60.0             # Maximum flight duration (seconds) - increased for longer test
control_frequency: 20.0        # Control loop frequency (Hz) - increased for faster response
stop_on_collision: true        # Stop simulation on collision

# Model Configuration (for model mode)
use_model: false               # Whether to use trained model
model_path: "models/vitlstm_best.pth"  # Path to trained model
model_type: "ViTLSTM"          # Model type
device: "auto"                 # Device for model inference

# Data Collection (for data_collection mode)
collect_data: false            # Whether to collect training data
data_output_dir: "collected_data"  # Output directory for collected data
num_trajectories: 10          # Number of trajectories to collect
trajectory_duration: 30.0     # Duration of each trajectory

# Visualization
enable_visualization: true     # Enable real-time visualization
show_obstacles: true          # Show detected obstacles
show_velocity_commands: true   # Show velocity command arrows

# Safety Parameters
enable_safety: true           # Enable safety features
min_altitude: -50.0           # Minimum altitude (AirSim coordinates)
max_altitude: -2.0            # Maximum altitude (AirSim coordinates)
safety_distance: 3.0          # Minimum distance from obstacles (increased for safety)

# Obstacle Detection
obstacle_inflation_factor: 1.0    # Obstacle inflation for safety (increased)
obstacle_distance_threshold: 10.0 # Maximum distance to consider obstacles (increased)
grid_center_offset: 10.0         # Grid center offset for path planning (increased)
grid_displacement: 0.3           # Grid resolution for path planning (finer resolution)

# Expert Policy Parameters
x_displacement: 5.0           # Forward displacement for waypoints (reduced for tighter turns)

# Logging
log_performance: true         # Log performance metrics
log_file: "simulation_log.txt"  # Log file name

# Example configurations for different modes:

# Expert Policy Mode (default)
# mode: "expert"
# collect_data: false
# use_model: false

# Model Inference Mode
# mode: "model"
# use_model: true
# model_path: "models/vitlstm_best.pth"
# model_type: "ViTLSTM"
# collect_data: false

# Data Collection Mode
# mode: "data_collection"
# collect_data: true
# num_trajectories: 20
# trajectory_duration: 45.0
# use_model: false

# High-speed testing
# desired_velocity: 7.0
# control_frequency: 30.0
# safety_distance: 1.5